### ISSUE TITLE
Fetch server data fails

### ISSUE THREAD

**Issue by LongnoseRob** [ac2cz/Falcon#87]
After upgrading to the 0.42 release of PacSatGround station  and the "reboot" of FS-3 I wanted to fetch the server data,

but this failes with an error dialog displayed.
in the log file the following text can be found:
`java.net.MalformedURLException: no protocol: tlm.amsatfox.org/FalconSat-3/TLMDB.tar.gz
        at java.base/java.net.URL.<init>(URL.java:672)
        at java.base/java.net.URL.<init>(URL.java:568)
        at java.base/java.net.URL.<init>(URL.java:515)
        at gui.MainWindow.downloadServerData(MainWindow.java:838)
        at gui.MainWindow.replaceServerData(MainWindow.java:807)
        at gui.MainWindow.actionPerformed(MainWindow.java:944)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
`

a wget on this url also fails:

`wget tlm.amsatfox.org/FalconSat-3/TMLDB.tar.gz
--2021-07-02 22:58:36--  http://tlm.amsatfox.org/FalconSat-3/TMLDB.tar.gz
Resolving tlm.amsatfox.org (tlm.amsatfox.org)... 34.211.233.168
Connecting to tlm.amsatfox.org (tlm.amsatfox.org)|34.211.233.168|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-02 22:58:42 ERROR 404: Not Found.`

I dont know if this is a problem on the server side, cause by the FS-3 "reboot"
or if this a problem of the 0.42 release

**Comment by ac2cz** [comment]
I may have messed up the URLs in the latest release.  This link works fine:
http://tlm.amsatfox.org/tlm/FalconSat-3/leaderboard.php?id=0&db=TLMDB

Thanks for the report. Let me see if I accidently changed the code

**Comment by ac2cz** [comment]
and hence this link works: https://tlm.amsatfox.org/tlm/FalconSat-3/TLMDB.tar.gz

**Comment by ac2cz** [comment]
Ok, a bug in the gui is overwriting the URL.  When you open the Spacecraft > FalconSat-3 screen it shows that the website has the same address as the telem server.  That is not correct.  If you paste this value into the Website URL: http://tlm.amsatfox.org/tlm and then save it should work.  If you re-open the Spacecraft > FalconSat-3 screen it will overwrite it again because it is initializing the screen from the wrong variable.  I will put out a fix for this.

**Comment by LongnoseRob** [comment]
Thanks!
with that quick fix it now started the download.
